name: Run Telegram Bot

on:
  schedule:
    - cron: '*/5 * * * *'  # كل 5 دقائق ليبقى نشطاً
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install pyrogram tgcrypto
      - run: python bot.py
        env:
          BOT_TOKEN: ${{ 8528552763:AAGeC9mncRX3HmHeUlg7PjJtMgnOC9ldTNM }}
          API_ID: ${{ 36260998 }}
          API_HASH: ${{ 09d7ea0ae63b70077839d7571e559544 }}
